### ISSUE TITLE
Dockerfile für Deployment

### ISSUE THREAD

**Issue by aaronschweig** [Stonks2Moon/Boersenclient#1]
Hallo,

ihr hattet ja bereits im .github-Repo ein Ticket eröffnet, damit dieser Service bereitgestellt werden kann. Dazu bräuchte ich noch eine `Dockerfile`. Wisst ihr wie ihr das macht, oder benötigt Ihr dafür Input?

**Comment by TimoScheuermann** [comment]
Bräuchten da Input deinerseits oder von @tjbnde

**Comment by aaronschweig** [comment]
@TimoScheuermann ich habe mal einen PR aufgemacht
