### ISSUE TITLE
Nutzung als CI/CD Test

### ISSUE THREAD

**Issue by aaronschweig** [Stonks2Moon/Boersenclient#3]
Hi,
ich wollte Fragen, ob es für euere Gruppe okay wäre, dass ich dieses Projekt nutze, um die Pipeline und das Zusammenspiel der Komponenten des Deployments zu testen?

Danke Schonmal!

**Comment by TimoScheuermann** [comment]
Wenn du die releases als Alpha markierst gerne

**Comment by aaronschweig** [comment]
Danke, die CI läuft soweit! Möchtest du direkt die funktionierende CI haben, oder warten, bis es generell in den anderen Repos verfügbar ist?
